version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: monorepo_dev_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/var/www
      - ./../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
